# Generated by Django 6.0.6 on 2026-06-23 00:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('category', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('inventory_quantity', models.PositiveIntegerField(default=0)),
                ('width', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('depth', models.DecimalField(decimal_places=2, help_text='Depth in inches', max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in inches', max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('material', models.CharField(max_length=120)),
                ('color', models.CharField(max_length=120)),
                ('recommended_space', models.CharField(choices=[('pantry', 'Pantry'), ('coffee_station', 'Coffee Station'), ('laundry_room', 'Laundry Room'), ('refrigerator', 'Refrigerator'), ('vanity', 'Vanity'), ('closet', 'Closet'), ('cabinet', 'Cabinet'), ('other', 'Other')], max_length=40)),
                ('recommended_style', models.CharField(choices=[('clear_acrylic', 'Clear Acrylic'), ('bamboo_natural', 'Bamboo / Natural'), ('white_minimal', 'White Minimal'), ('cream_neutral', 'Cream Neutral'), ('mixed', 'Mixed')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='catalog_pro_name_f603c0_idx'), models.Index(fields=['sku'], name='catalog_pro_sku_2c4c34_idx'), models.Index(fields=['category'], name='catalog_pro_categor_50f92a_idx'), models.Index(fields=['recommended_space'], name='catalog_pro_recomme_2e7c91_idx'), models.Index(fields=['recommended_style'], name='catalog_pro_recomme_570757_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product-images/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=180)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
